/**
 * IndianRailAPI Integration & Pan-India Geographical Station/Train/Corridor Registry
 * API Endpoint: http://indianrailapi.com/api/v2/StationLocationOnMap/apikey/<apikey>/StationCode/<StationCode>
 */

export interface GeoStation {
  name: string;
  code: string;
  lat: number;
  lng: number;
  km: number;
  division: string;
  zone: string;
  state: string;
  elevationM: number;
  platforms: number;
  interlockingType: string;
  kavachEnabled: boolean;
  corridorId: string;
  isJunction?: boolean;
  apiSynced?: boolean;
}

export interface GeoTrain {
  number: string;
  name: string;
  type:
    | "VANDE_BHARAT"
    | "RAJDHANI"
    | "SHATABDI_GATIMAAN"
    | "SUPERFAST"
    | "EXPRESS"
    | "FREIGHT_CONTAINER"
    | "MAINTENANCE_SPECIAL";
  lat: number;
  lng: number;
  speedKmh: number;
  headingDeg: number;
  origin: string;
  destination: string;
  nextStation: string;
  status: "ON_TIME" | "DELAYED" | "HELD_LOOP" | "WORK_ZONE";
  delayMins: number;
  signalAspect: "DOUBLE_GREEN" | "GREEN" | "YELLOW" | "RED";
  corridorId: string;
}

export interface NationalCorridor {
  id: string;
  code: string;
  name: string;
  type: "GOLDEN_QUADRILATERAL" | "DIAGONAL" | "HIGH_SPEED_DEDICATED" | "COASTAL" | "TRUNK" | "DEDICATED_FREIGHT";
  lengthKm: number;
  densityGmt: number;
  maxSpeedKmh: number;
  electrified: boolean;
  tracks: number;
  stations: string[]; // station codes in sequence
  status?: "Operational" | "Announced in Budget 2021–22" | "Announced in Budget 2026–27" | "Proposed";
  startPoint?: string;
  terminationPoint?: string;
  logisticsHub?: string;
}

export const NATIONAL_CORRIDORS: NationalCorridor[] = [
  {
    id: "GQ-DELHI-MUMBAI",
    code: "GQ-01",
    name: "Delhi ↔ Mumbai Central (Western Trunk)",
    type: "GOLDEN_QUADRILATERAL",
    lengthKm: 1386,
    densityGmt: 88,
    maxSpeedKmh: 160,
    electrified: true,
    tracks: 4,
    stations: ["NDLS", "NZM", "FDB", "PWL", "MTJ", "BTE", "KOTA", "RTM", "BRC", "ST", "BVI", "MMCT"],
  },
  {
    id: "GQ-DELHI-HOWRAH",
    code: "GQ-02",
    name: "Delhi ↔ Howrah (Eastern Trunk)",
    type: "GOLDEN_QUADRILATERAL",
    lengthKm: 1447,
    densityGmt: 94,
    maxSpeedKmh: 160,
    electrified: true,
    tracks: 4,
    stations: ["NDLS", "ALJN", "TDL", "CNB", "FTP", "PRYJ", "DDU", "GAYA", "DHN", "ASN", "HWH"],
  },
  {
    id: "GQ-DELHI-CHENNAI",
    code: "GQ-03",
    name: "Delhi ↔ Chennai Central (Grand Trunk)",
    type: "GOLDEN_QUADRILATERAL",
    lengthKm: 2182,
    densityGmt: 74,
    maxSpeedKmh: 140,
    electrified: true,
    tracks: 3,
    stations: ["NDLS", "MTJ", "AGC", "GWL", "VGLB", "BPL", "ET", "NGP", "BPQ", "WL", "BZA", "MAS"],
  },
  {
    id: "GQ-MUMBAI-HOWRAH",
    code: "GQ-04",
    name: "Mumbai CSMT ↔ Howrah (Central Trunk)",
    type: "GOLDEN_QUADRILATERAL",
    lengthKm: 1968,
    densityGmt: 82,
    maxSpeedKmh: 130,
    electrified: true,
    tracks: 3,
    stations: ["CSMT", "KYN", "NK", "BSL", "NGP", "DURG", "R", "BSP", "ROU", "TATA", "KGP", "HWH"],
  },
  {
    id: "GQ-MUMBAI-CHENNAI",
    code: "GQ-05",
    name: "Mumbai ↔ Chennai Central",
    type: "GOLDEN_QUADRILATERAL",
    lengthKm: 1281,
    densityGmt: 68,
    maxSpeedKmh: 130,
    electrified: true,
    tracks: 2,
    stations: ["CSMT", "PUNE", "SUR", "WADI", "GTL", "RU", "MAS"],
  },
  {
    id: "GQ-CHENNAI-HOWRAH",
    code: "GQ-06",
    name: "Chennai Central ↔ Howrah (East Coast Trunk)",
    type: "GOLDEN_QUADRILATERAL",
    lengthKm: 1661,
    densityGmt: 72,
    maxSpeedKmh: 130,
    electrified: true,
    tracks: 2,
    stations: ["MAS", "NLR", "OGL", "BZA", "RJY", "VSKP", "BAM", "KUR", "BBS", "CTC", "BHC", "KGP", "HWH"],
  },
  {
    id: "DIAG-DELHI-BENGALURU",
    code: "DIAG-01",
    name: "Delhi ↔ Bengaluru City (Karnataka Corridor)",
    type: "DIAGONAL",
    lengthKm: 2365,
    densityGmt: 65,
    maxSpeedKmh: 130,
    electrified: true,
    tracks: 2,
    stations: ["NZM", "AGC", "VGLB", "BPL", "NGP", "SC", "WADI", "RC", "GTL", "DMM", "YPR", "SBC"],
  },
  {
    id: "COR-NORTH-HIGH-SPEED",
    code: "NHS-01",
    name: "Delhi ↔ Amritsar / Katra (Northern Corridor)",
    type: "HIGH_SPEED_DEDICATED",
    lengthKm: 655,
    densityGmt: 78,
    maxSpeedKmh: 160,
    electrified: true,
    tracks: 4,
    stations: ["NDLS", "PNP", "UMB", "CDG", "LDH", "JUC", "ASR", "JAT", "SVDK"],
  },
  {
    id: "COR-KONKAN-COAST",
    code: "COAST-01",
    name: "Konkan Railway (Mumbai ↔ Goa ↔ Kerala)",
    type: "COASTAL",
    lengthKm: 1510,
    densityGmt: 58,
    maxSpeedKmh: 130,
    electrified: true,
    tracks: 2,
    stations: ["CSMT", "PNVL", "ROHA", "RN", "MAO", "KAWR", "UD", "MAJN", "CAN", "CLT", "SRR", "ERS", "TVC"],
  },
  {
    id: "COR-NORTHEAST-TRUNK",
    code: "NE-01",
    name: "Howrah / Patna ↔ Guwahati ↔ Dibrugarh",
    type: "TRUNK",
    lengthKm: 1540,
    densityGmt: 54,
    maxSpeedKmh: 130,
    electrified: true,
    tracks: 2,
    stations: ["HWH", "MLDT", "KIR", "NJP", "NBQ", "KYQ", "GHY", "LMG", "MXN", "DBRG"],
  },

  // =========================================================================
  // DEDICATED FREIGHT CORRIDORS (DFC) OF INDIA (NATIONAL RAIL PLAN / DFCIL)
  // =========================================================================
  {
    id: "DFC-EASTERN",
    code: "EDFC",
    name: "Eastern Dedicated Freight Corridor (EDFC)",
    type: "DEDICATED_FREIGHT",
    lengthKm: 1337,
    status: "Operational",
    startPoint: "Ludhiana",
    terminationPoint: "Dankuni",
    logisticsHub: "Meerut",
    densityGmt: 120,
    maxSpeedKmh: 100,
    electrified: true,
    tracks: 2,
    stations: ["SNL", "LDH", "UMB", "SRE", "MTC", "KRJ", "TDL", "CNB", "PRYJ", "DDU", "SEB", "GMO", "ASN", "DKAE"],
  },
  {
    id: "DFC-WESTERN",
    code: "WDFC",
    name: "Western Dedicated Freight Corridor (WDFC)",
    type: "DEDICATED_FREIGHT",
    lengthKm: 1504,
    status: "Operational",
    startPoint: "Dadri",
    terminationPoint: "JNPT, Nava Sheva",
    logisticsHub: "Dadri Multimodal Logistics Park",
    densityGmt: 135,
    maxSpeedKmh: 100,
    electrified: true,
    tracks: 2,
    stations: ["DER", "RE", "FL", "MJ", "PNU", "MSH", "ADI", "BRC", "ST", "BSR", "JNPT"],
  },
  {
    id: "DFC-EAST-WEST",
    code: "EW-DFC",
    name: "East-West Dedicated Freight Corridor",
    type: "DEDICATED_FREIGHT",
    lengthKm: 2000,
    status: "Announced in Budget 2021–22",
    startPoint: "Dankuni",
    terminationPoint: "Bhusawal",
    densityGmt: 95,
    maxSpeedKmh: 100,
    electrified: true,
    tracks: 2,
    stations: ["DKAE", "KGP", "TATA", "ROU", "JSG", "BSP", "R", "DURG", "NGP", "WR", "BD", "AK", "BSL"],
  },
  {
    id: "DFC-NORTH-SOUTH",
    code: "NS-DFC",
    name: "North-South Dedicated Freight Corridor",
    type: "DEDICATED_FREIGHT",
    lengthKm: 975,
    status: "Announced in Budget 2021–22",
    startPoint: "Vijayawada",
    terminationPoint: "Itarsi",
    densityGmt: 90,
    maxSpeedKmh: 100,
    electrified: true,
    tracks: 2,
    stations: ["BZA", "KMT", "WL", "RDM", "BPQ", "NGP", "BZU", "ET"],
  },
  {
    id: "DFC-EAST-COAST",
    code: "EC-DFC",
    name: "East Coast Dedicated Freight Corridor",
    type: "DEDICATED_FREIGHT",
    lengthKm: 1115,
    status: "Announced in Budget 2021–22",
    startPoint: "Kharagpur",
    terminationPoint: "Vijayawada",
    densityGmt: 85,
    maxSpeedKmh: 100,
    electrified: true,
    tracks: 2,
    stations: ["KGP", "BLS", "BHC", "CTC", "BBS", "KUR", "BAM", "VSKP", "RJY", "EE", "BZA"],
  },
  {
    id: "DFC-EAST-WEST-DANKUNI-SURAT",
    code: "EW-DS",
    name: "East-West DFC (Dankuni ↔ Surat)",
    type: "DEDICATED_FREIGHT",
    lengthKm: 2052,
    status: "Announced in Budget 2026–27",
    startPoint: "Dankuni",
    terminationPoint: "Surat",
    densityGmt: 92,
    maxSpeedKmh: 100,
    electrified: true,
    tracks: 2,
    stations: ["DKAE", "ASN", "DHN", "RNC", "ROU", "BSP", "R", "DURG", "NGP", "BSL", "JL", "NDB", "ST"],
  },
  {
    id: "DFC-SOUTHERN",
    code: "S-DFC",
    name: "Southern Dedicated Freight Corridor",
    type: "DEDICATED_FREIGHT",
    lengthKm: 892,
    status: "Proposed",
    startPoint: "Madgaon",
    terminationPoint: "Chennai",
    densityGmt: 75,
    maxSpeedKmh: 100,
    electrified: true,
    tracks: 2,
    stations: ["MAO", "LD", "UBL", "HPT", "BAY", "GTL", "RU", "AJJ", "MAS"],
  },
];

// Comprehensive Pan-India Stations Database (GPS, Elevation, Platforms, Interlocking, Kavach)
export const PRE_SEEDED_STATIONS: GeoStation[] = [
  // --- NATIONAL CAPITAL REGION & NORTHERN RAILWAY ---
  {
    name: "New Delhi",
    code: "NDLS",
    lat: 28.6415,
    lng: 77.2207,
    km: 0,
    division: "Delhi",
    zone: "NR",
    state: "Delhi",
    elevationM: 214,
    platforms: 16,
    interlockingType: "Route Relay Electronic Interlocking (RRI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-MUMBAI",
    isJunction: true,
  },
  {
    name: "Hazrat Nizamuddin",
    code: "NZM",
    lat: 28.5888,
    lng: 77.2533,
    km: 7,
    division: "Delhi",
    zone: "NR",
    state: "Delhi",
    elevationM: 211,
    platforms: 9,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-MUMBAI",
    isJunction: true,
  },
  {
    name: "Faridabad",
    code: "FDB",
    lat: 28.4089,
    lng: 77.3178,
    km: 28,
    division: "Delhi",
    zone: "NR",
    state: "Haryana",
    elevationM: 206,
    platforms: 4,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-MUMBAI",
  },
  {
    name: "Palwal",
    code: "PWL",
    lat: 28.1487,
    lng: 77.326,
    km: 58,
    division: "Delhi",
    zone: "NR",
    state: "Haryana",
    elevationM: 198,
    platforms: 5,
    interlockingType: "Solid State Interlocking (SSI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-MUMBAI",
    isJunction: true,
  },
  {
    name: "Panipat Junction",
    code: "PNP",
    lat: 29.3909,
    lng: 76.9635,
    km: 89,
    division: "Delhi",
    zone: "NR",
    state: "Haryana",
    elevationM: 222,
    platforms: 5,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "COR-NORTH-HIGH-SPEED",
    isJunction: true,
  },
  {
    name: "Ambala Cantt Junction",
    code: "UMB",
    lat: 30.3344,
    lng: 76.8286,
    km: 198,
    division: "Ambala",
    zone: "NR",
    state: "Haryana",
    elevationM: 272,
    platforms: 8,
    interlockingType: "Route Relay Interlocking (RRI)",
    kavachEnabled: true,
    corridorId: "COR-NORTH-HIGH-SPEED",
    isJunction: true,
  },
  {
    name: "Chandigarh Junction",
    code: "CDG",
    lat: 30.7028,
    lng: 76.8208,
    km: 244,
    division: "Ambala",
    zone: "NR",
    state: "Chandigarh",
    elevationM: 320,
    platforms: 6,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "COR-NORTH-HIGH-SPEED",
    isJunction: true,
  },
  {
    name: "Ludhiana Junction",
    code: "LDH",
    lat: 30.9082,
    lng: 75.8587,
    km: 312,
    division: "Firozpur",
    zone: "NR",
    state: "Punjab",
    elevationM: 247,
    platforms: 7,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "COR-NORTH-HIGH-SPEED",
    isJunction: true,
  },
  {
    name: "Amritsar Junction",
    code: "ASR",
    lat: 31.6339,
    lng: 74.8655,
    km: 448,
    division: "Firozpur",
    zone: "NR",
    state: "Punjab",
    elevationM: 233,
    platforms: 6,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "COR-NORTH-HIGH-SPEED",
    isJunction: true,
  },
  {
    name: "Jammu Tawi",
    code: "JAT",
    lat: 32.7061,
    lng: 74.8798,
    km: 577,
    division: "Firozpur",
    zone: "NR",
    state: "Jammu & Kashmir",
    elevationM: 344,
    platforms: 4,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "COR-NORTH-HIGH-SPEED",
    isJunction: true,
  },
  {
    name: "SMVD Katra",
    code: "SVDK",
    lat: 32.9934,
    lng: 74.9318,
    km: 655,
    division: "Firozpur",
    zone: "NR",
    state: "Jammu & Kashmir",
    elevationM: 813,
    platforms: 5,
    interlockingType: "State-of-the-Art Electronic Interlocking",
    kavachEnabled: true,
    corridorId: "COR-NORTH-HIGH-SPEED",
  },

  // --- UTTAR PRADESH & NORTH CENTRAL RAILWAY ---
  {
    name: "Mathura Junction",
    code: "MTJ",
    lat: 27.4924,
    lng: 77.6737,
    km: 140,
    division: "Agra",
    zone: "NCR",
    state: "Uttar Pradesh",
    elevationM: 177,
    platforms: 10,
    interlockingType: "Route Relay Electronic Interlocking (RRI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-MUMBAI",
    isJunction: true,
  },
  {
    name: "Agra Cantt",
    code: "AGC",
    lat: 27.1592,
    lng: 77.9904,
    km: 195,
    division: "Agra",
    zone: "NCR",
    state: "Uttar Pradesh",
    elevationM: 168,
    platforms: 6,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-CHENNAI",
    isJunction: true,
  },
  {
    name: "Aligarh Junction",
    code: "ALJN",
    lat: 27.8974,
    lng: 78.0772,
    km: 131,
    division: "Prayagraj",
    zone: "NCR",
    state: "Uttar Pradesh",
    elevationM: 186,
    platforms: 7,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-HOWRAH",
    isJunction: true,
  },
  {
    name: "Tundla Junction",
    code: "TDL",
    lat: 27.2081,
    lng: 78.2384,
    km: 204,
    division: "Prayagraj",
    zone: "NCR",
    state: "Uttar Pradesh",
    elevationM: 167,
    platforms: 5,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-HOWRAH",
    isJunction: true,
  },
  {
    name: "Kanpur Central",
    code: "CNB",
    lat: 26.4537,
    lng: 80.3514,
    km: 435,
    division: "Prayagraj",
    zone: "NCR",
    state: "Uttar Pradesh",
    elevationM: 127,
    platforms: 10,
    interlockingType: "Route Relay Interlocking (RRI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-HOWRAH",
    isJunction: true,
  },
  {
    name: "Lucknow Charbagh",
    code: "LKO",
    lat: 26.8322,
    lng: 80.9189,
    km: 507,
    division: "Lucknow",
    zone: "NR",
    state: "Uttar Pradesh",
    elevationM: 123,
    platforms: 9,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-HOWRAH",
    isJunction: true,
  },
  {
    name: "Prayagraj Junction",
    code: "PRYJ",
    lat: 25.4497,
    lng: 81.8315,
    km: 628,
    division: "Prayagraj",
    zone: "NCR",
    state: "Uttar Pradesh",
    elevationM: 100,
    platforms: 10,
    interlockingType: "Route Relay Electronic Interlocking (RRI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-HOWRAH",
    isJunction: true,
  },
  {
    name: "Pt. Deen Dayal Upadhyaya Jn",
    code: "DDU",
    lat: 25.2818,
    lng: 83.1189,
    km: 781,
    division: "DDU",
    zone: "ECR",
    state: "Uttar Pradesh",
    elevationM: 78,
    platforms: 8,
    interlockingType: "Asia's Largest Route Relay Interlocking Yard",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-HOWRAH",
    isJunction: true,
  },
  {
    name: "Varanasi Junction",
    code: "BSB",
    lat: 25.3283,
    lng: 82.9866,
    km: 797,
    division: "Varanasi",
    zone: "NER",
    state: "Uttar Pradesh",
    elevationM: 81,
    platforms: 9,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-HOWRAH",
    isJunction: true,
  },

  // --- BIHAR, JHARKHAND, WEST BENGAL & EASTERN ZONE ---
  {
    name: "Gaya Junction",
    code: "GAYA",
    lat: 24.8051,
    lng: 84.9989,
    km: 987,
    division: "DDU",
    zone: "ECR",
    state: "Bihar",
    elevationM: 117,
    platforms: 9,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-HOWRAH",
    isJunction: true,
  },
  {
    name: "Patna Junction",
    code: "PNBE",
    lat: 25.6022,
    lng: 85.1376,
    km: 998,
    division: "Danapur",
    zone: "ECR",
    state: "Bihar",
    elevationM: 53,
    platforms: 10,
    interlockingType: "Route Relay Electronic Interlocking (RRI)",
    kavachEnabled: true,
    corridorId: "COR-NORTHEAST-TRUNK",
    isJunction: true,
  },
  {
    name: "Dhanbad Junction",
    code: "DHN",
    lat: 23.7957,
    lng: 86.4304,
    km: 1190,
    division: "Dhanbad",
    zone: "ECR",
    state: "Jharkhand",
    elevationM: 227,
    platforms: 8,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-HOWRAH",
    isJunction: true,
  },
  {
    name: "Tatanagar Junction",
    code: "TATA",
    lat: 22.7667,
    lng: 86.1994,
    km: 1718,
    division: "Chakradharpur",
    zone: "SER",
    state: "Jharkhand",
    elevationM: 165,
    platforms: 5,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "GQ-MUMBAI-HOWRAH",
    isJunction: true,
  },
  {
    name: "Asansol Junction",
    code: "ASN",
    lat: 23.6871,
    lng: 86.9746,
    km: 1248,
    division: "Asansol",
    zone: "ER",
    state: "West Bengal",
    elevationM: 126,
    platforms: 7,
    interlockingType: "Route Relay Interlocking (RRI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-HOWRAH",
    isJunction: true,
  },
  {
    name: "Kharagpur Junction",
    code: "KGP",
    lat: 22.3323,
    lng: 87.3235,
    km: 1332,
    division: "Kharagpur",
    zone: "SER",
    state: "West Bengal",
    elevationM: 40,
    platforms: 12,
    interlockingType: "World-Renowned Extended Platform Interlocking (1072m)",
    kavachEnabled: true,
    corridorId: "GQ-CHENNAI-HOWRAH",
    isJunction: true,
  },
  {
    name: "Howrah Junction",
    code: "HWH",
    lat: 22.5838,
    lng: 88.3426,
    km: 1447,
    division: "Howrah",
    zone: "ER",
    state: "West Bengal",
    elevationM: 12,
    platforms: 23,
    interlockingType: "Busiest Railway Terminal in India (Route Relay)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-HOWRAH",
    isJunction: true,
  },
  {
    name: "New Jalpaiguri Junction",
    code: "NJP",
    lat: 26.6858,
    lng: 88.4429,
    km: 1572,
    division: "Katihar",
    zone: "NFR",
    state: "West Bengal",
    elevationM: 119,
    platforms: 6,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "COR-NORTHEAST-TRUNK",
    isJunction: true,
  },
  {
    name: "Guwahati",
    code: "GHY",
    lat: 26.1824,
    lng: 91.7519,
    km: 1980,
    division: "Lumding",
    zone: "NFR",
    state: "Assam",
    elevationM: 54,
    platforms: 7,
    interlockingType: "Solar-Powered High-Capacity Interlocking",
    kavachEnabled: true,
    corridorId: "COR-NORTHEAST-TRUNK",
    isJunction: true,
  },

  // --- RAJASTHAN, GUJARAT & WESTERN ZONE ---
  {
    name: "Kota Junction",
    code: "KOTA",
    lat: 25.2185,
    lng: 75.8648,
    km: 466,
    division: "Kota",
    zone: "WCR",
    state: "Rajasthan",
    elevationM: 253,
    platforms: 6,
    interlockingType: "Route Relay Electronic Interlocking (RRI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-MUMBAI",
    isJunction: true,
  },
  {
    name: "Jaipur Junction",
    code: "JP",
    lat: 26.9196,
    lng: 75.7878,
    km: 308,
    division: "Jaipur",
    zone: "NWR",
    state: "Rajasthan",
    elevationM: 428,
    platforms: 8,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-MUMBAI",
    isJunction: true,
  },
  {
    name: "Ratlam Junction",
    code: "RTM",
    lat: 23.3441,
    lng: 75.0427,
    km: 732,
    division: "Ratlam",
    zone: "WR",
    state: "Madhya Pradesh",
    elevationM: 494,
    platforms: 7,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-MUMBAI",
    isJunction: true,
  },
  {
    name: "Vadodara Junction",
    code: "BRC",
    lat: 22.3107,
    lng: 73.1812,
    km: 992,
    division: "Vadodara",
    zone: "WR",
    state: "Gujarat",
    elevationM: 36,
    platforms: 7,
    interlockingType: "Route Relay Interlocking (RRI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-MUMBAI",
    isJunction: true,
  },
  {
    name: "Ahmedabad Junction",
    code: "ADI",
    lat: 23.0232,
    lng: 72.6009,
    km: 1092,
    division: "Ahmedabad",
    zone: "WR",
    state: "Gujarat",
    elevationM: 53,
    platforms: 12,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-MUMBAI",
    isJunction: true,
  },
  {
    name: "Surat",
    code: "ST",
    lat: 21.2049,
    lng: 72.8411,
    km: 1122,
    division: "Mumbai WR",
    zone: "WR",
    state: "Gujarat",
    elevationM: 21,
    platforms: 4,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-MUMBAI",
    isJunction: true,
  },

  // --- MAHARASHTRA & CENTRAL ZONE ---
  {
    name: "Mumbai Central",
    code: "MMCT",
    lat: 18.9696,
    lng: 72.8193,
    km: 1386,
    division: "Mumbai WR",
    zone: "WR",
    state: "Maharashtra",
    elevationM: 7,
    platforms: 9,
    interlockingType: "Electronic Route Interlocking",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-MUMBAI",
    isJunction: true,
  },
  {
    name: "Chhatrapati Shivaji Maharaj Terminus",
    code: "CSMT",
    lat: 18.9401,
    lng: 72.8354,
    km: 1388,
    division: "Mumbai CR",
    zone: "CR",
    state: "Maharashtra",
    elevationM: 10,
    platforms: 18,
    interlockingType: "UNESCO Heritage High-Capacity Electronic Interlocking",
    kavachEnabled: true,
    corridorId: "GQ-MUMBAI-HOWRAH",
    isJunction: true,
  },
  {
    name: "Pune Junction",
    code: "PUNE",
    lat: 18.5284,
    lng: 73.8739,
    km: 192,
    division: "Pune",
    zone: "CR",
    state: "Maharashtra",
    elevationM: 560,
    platforms: 6,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "GQ-MUMBAI-CHENNAI",
    isJunction: true,
  },
  {
    name: "Bhusawal Junction",
    code: "BSL",
    lat: 21.0456,
    lng: 75.7923,
    km: 440,
    division: "Bhusawal",
    zone: "CR",
    state: "Maharashtra",
    elevationM: 205,
    platforms: 8,
    interlockingType: "Route Relay Interlocking (RRI)",
    kavachEnabled: true,
    corridorId: "GQ-MUMBAI-HOWRAH",
    isJunction: true,
  },
  {
    name: "Nagpur Junction",
    code: "NGP",
    lat: 21.1524,
    lng: 79.0888,
    km: 837,
    division: "Nagpur",
    zone: "CR",
    state: "Maharashtra",
    elevationM: 310,
    platforms: 8,
    interlockingType: "Diamond Crossing Hub Electronic Interlocking",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-CHENNAI",
    isJunction: true,
  },

  // --- MADHYA PRADESH & CHHATTISGARH ---
  {
    name: "Gwalior Junction",
    code: "GWL",
    lat: 26.2163,
    lng: 78.1884,
    km: 313,
    division: "Jhansi",
    zone: "NCR",
    state: "Madhya Pradesh",
    elevationM: 212,
    platforms: 5,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-CHENNAI",
    isJunction: true,
  },
  {
    name: "Virangana Lakshmibai Jhansi",
    code: "VGLB",
    lat: 25.4484,
    lng: 78.5583,
    km: 410,
    division: "Jhansi",
    zone: "NCR",
    state: "Uttar Pradesh",
    elevationM: 258,
    platforms: 8,
    interlockingType: "Route Relay Electronic Interlocking (RRI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-CHENNAI",
    isJunction: true,
  },
  {
    name: "Bhopal Junction",
    code: "BPL",
    lat: 23.2663,
    lng: 77.4116,
    km: 702,
    division: "Bhopal",
    zone: "WCR",
    state: "Madhya Pradesh",
    elevationM: 505,
    platforms: 6,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-CHENNAI",
    isJunction: true,
  },
  {
    name: "Itarsi Junction",
    code: "ET",
    lat: 22.6133,
    lng: 77.7618,
    km: 794,
    division: "Bhopal",
    zone: "WCR",
    state: "Madhya Pradesh",
    elevationM: 304,
    platforms: 8,
    interlockingType: "Critical North-South-East-West Diamond Interlocking",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-CHENNAI",
    isJunction: true,
  },
  {
    name: "Raipur Junction",
    code: "R",
    lat: 21.2583,
    lng: 81.6296,
    km: 1108,
    division: "Raipur",
    zone: "SECR",
    state: "Chhattisgarh",
    elevationM: 298,
    platforms: 7,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "GQ-MUMBAI-HOWRAH",
    isJunction: true,
  },
  {
    name: "Bilaspur Junction",
    code: "BSP",
    lat: 22.0797,
    lng: 82.1648,
    km: 1219,
    division: "Bilaspur",
    zone: "SECR",
    state: "Chhattisgarh",
    elevationM: 268,
    platforms: 8,
    interlockingType: "SECR Freight HQ Electronic Interlocking",
    kavachEnabled: true,
    corridorId: "GQ-MUMBAI-HOWRAH",
    isJunction: true,
  },

  // --- ODISHA, ANDHRA PRADESH & TELANGANA ---
  {
    name: "Bhubaneswar",
    code: "BBS",
    lat: 20.2648,
    lng: 85.8427,
    km: 1225,
    division: "Khurda Road",
    zone: "ECoR",
    state: "Odisha",
    elevationM: 33,
    platforms: 6,
    interlockingType: "Route Relay Electronic Interlocking",
    kavachEnabled: true,
    corridorId: "GQ-CHENNAI-HOWRAH",
    isJunction: true,
  },
  {
    name: "Visakhapatnam Junction",
    code: "VSKP",
    lat: 17.7215,
    lng: 83.2872,
    km: 880,
    division: "Waltair",
    zone: "ECoR",
    state: "Andhra Pradesh",
    elevationM: 12,
    platforms: 8,
    interlockingType: "Route Relay Interlocking (RRI)",
    kavachEnabled: true,
    corridorId: "GQ-CHENNAI-HOWRAH",
    isJunction: true,
  },
  {
    name: "Vijayawada Junction",
    code: "BZA",
    lat: 16.5186,
    lng: 80.6198,
    km: 1748,
    division: "Vijayawada",
    zone: "SCR",
    state: "Andhra Pradesh",
    elevationM: 19,
    platforms: 10,
    interlockingType: "SCR Multi-Directional Route Relay Interlocking",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-CHENNAI",
    isJunction: true,
  },
  {
    name: "Secunderabad Junction",
    code: "SC",
    lat: 17.4339,
    lng: 78.5044,
    km: 1667,
    division: "Secunderabad",
    zone: "SCR",
    state: "Telangana",
    elevationM: 536,
    platforms: 10,
    interlockingType: "State-of-the-art Kavach Pioneer Interlocking",
    kavachEnabled: true,
    corridorId: "DIAG-DELHI-BENGALURU",
    isJunction: true,
  },

  // --- TAMIL NADU, KARNATAKA, KERALA & GOA ---
  {
    name: "MGR Chennai Central",
    code: "MAS",
    lat: 13.0827,
    lng: 80.2755,
    km: 2182,
    division: "Chennai",
    zone: "SR",
    state: "Tamil Nadu",
    elevationM: 7,
    platforms: 15,
    interlockingType: "Southern Railway Gateway Route Relay",
    kavachEnabled: true,
    corridorId: "GQ-DELHI-CHENNAI",
    isJunction: true,
  },
  {
    name: "KSR Bengaluru City",
    code: "SBC",
    lat: 12.9781,
    lng: 77.5696,
    km: 2365,
    division: "Bengaluru",
    zone: "SWR",
    state: "Karnataka",
    elevationM: 920,
    platforms: 10,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DIAG-DELHI-BENGALURU",
    isJunction: true,
  },
  {
    name: "Madgaon Junction",
    code: "MAO",
    lat: 15.2736,
    lng: 73.9788,
    km: 670,
    division: "Karwar",
    zone: "KR",
    state: "Goa",
    elevationM: 9,
    platforms: 4,
    interlockingType: "Konkan Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "COR-KONKAN-COAST",
    isJunction: true,
  },
  {
    name: "Ernakulam Junction (South)",
    code: "ERS",
    lat: 9.9678,
    lng: 76.2891,
    km: 1290,
    division: "Thiruvananthapuram",
    zone: "SR",
    state: "Kerala",
    elevationM: 3,
    platforms: 6,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "COR-KONKAN-COAST",
    isJunction: true,
  },
  {
    name: "Thiruvananthapuram Central",
    code: "TVC",
    lat: 8.4875,
    lng: 76.9525,
    km: 1510,
    division: "Thiruvananthapuram",
    zone: "SR",
    state: "Kerala",
    elevationM: 10,
    platforms: 5,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "COR-KONKAN-COAST",
    isJunction: true,
  },

  // --- DEDICATED FREIGHT CORRIDOR (DFC) TERMINALS & STRATEGIC NODES ---
  {
    name: "Dankuni Junction (DFC Eastern Terminal)",
    code: "DKAE",
    lat: 22.6845,
    lng: 88.2974,
    km: 1337,
    division: "Howrah",
    zone: "ER",
    state: "West Bengal",
    elevationM: 9,
    platforms: 6,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-EASTERN",
    isJunction: true,
  },
  {
    name: "Sahnewal / Ludhiana DFC Yard",
    code: "SNL",
    lat: 30.8496,
    lng: 75.9863,
    km: 0,
    division: "Firozpur",
    zone: "NR",
    state: "Punjab",
    elevationM: 254,
    platforms: 4,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-EASTERN",
    isJunction: true,
  },
  {
    name: "Dadri Multimodal Logistics Yard",
    code: "DER",
    lat: 28.5583,
    lng: 77.5542,
    km: 0,
    division: "Delhi",
    zone: "NCR",
    state: "Uttar Pradesh",
    elevationM: 206,
    platforms: 6,
    interlockingType: "Automatic Route Electronic Interlocking",
    kavachEnabled: true,
    corridorId: "DFC-WESTERN",
    isJunction: true,
  },
  {
    name: "JNPT / Nava Sheva Terminal",
    code: "JNPT",
    lat: 18.9482,
    lng: 72.9510,
    km: 1504,
    division: "Mumbai CR",
    zone: "CR",
    state: "Maharashtra",
    elevationM: 6,
    platforms: 8,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-WESTERN",
    isJunction: true,
  },
  {
    name: "Meerut City (EDFC Logistics Hub)",
    code: "MTC",
    lat: 28.9800,
    lng: 77.6890,
    km: 140,
    division: "Delhi",
    zone: "NR",
    state: "Uttar Pradesh",
    elevationM: 224,
    platforms: 5,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-EASTERN",
    isJunction: true,
  },
  {
    name: "Saharanpur Junction",
    code: "SRE",
    lat: 29.9671,
    lng: 77.5452,
    km: 210,
    division: "Ambala",
    zone: "NR",
    state: "Uttar Pradesh",
    elevationM: 275,
    platforms: 6,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-EASTERN",
    isJunction: true,
  },
  {
    name: "Khurja Junction",
    code: "KRJ",
    lat: 28.2562,
    lng: 77.8540,
    km: 320,
    division: "Prayagraj",
    zone: "NCR",
    state: "Uttar Pradesh",
    elevationM: 195,
    platforms: 5,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-EASTERN",
    isJunction: true,
  },
  {
    name: "Sonnagar Junction",
    code: "SEB",
    lat: 24.9123,
    lng: 84.1843,
    km: 890,
    division: "Pt. Deen Dayal Upadhyaya",
    zone: "ECR",
    state: "Bihar",
    elevationM: 108,
    platforms: 4,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-EASTERN",
    isJunction: true,
  },
  {
    name: "Rewari Junction",
    code: "RE",
    lat: 28.1928,
    lng: 76.6239,
    km: 82,
    division: "Jaipur",
    zone: "NWR",
    state: "Haryana",
    elevationM: 245,
    platforms: 8,
    interlockingType: "Route Relay Interlocking (RRI)",
    kavachEnabled: true,
    corridorId: "DFC-WESTERN",
    isJunction: true,
  },
  {
    name: "Phulera Junction",
    code: "FL",
    lat: 26.8732,
    lng: 75.2396,
    km: 295,
    division: "Jaipur",
    zone: "NWR",
    state: "Rajasthan",
    elevationM: 386,
    platforms: 5,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-WESTERN",
    isJunction: true,
  },
  {
    name: "Marwar Junction",
    code: "MJ",
    lat: 25.7333,
    lng: 73.6167,
    km: 512,
    division: "Ajmer",
    zone: "NWR",
    state: "Rajasthan",
    elevationM: 267,
    platforms: 4,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-WESTERN",
    isJunction: true,
  },
  {
    name: "Palanpur Junction",
    code: "PNU",
    lat: 24.1722,
    lng: 72.4281,
    km: 740,
    division: "Ahmedabad",
    zone: "WR",
    state: "Gujarat",
    elevationM: 231,
    platforms: 5,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-WESTERN",
    isJunction: true,
  },
  {
    name: "Mehsana Junction",
    code: "MSH",
    lat: 23.5960,
    lng: 72.3918,
    km: 805,
    division: "Ahmedabad",
    zone: "WR",
    state: "Gujarat",
    elevationM: 93,
    platforms: 6,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-WESTERN",
    isJunction: true,
  },
  {
    name: "Vasai Road Junction",
    code: "BSR",
    lat: 19.3811,
    lng: 72.8311,
    km: 1440,
    division: "Mumbai WR",
    zone: "WR",
    state: "Maharashtra",
    elevationM: 7,
    platforms: 7,
    interlockingType: "Electronic Route Interlocking",
    kavachEnabled: true,
    corridorId: "DFC-WESTERN",
    isJunction: true,
  },
  {
    name: "Itarsi Junction (North-South Terminal)",
    code: "ET",
    lat: 22.6139,
    lng: 77.7634,
    km: 0,
    division: "Bhopal",
    zone: "WCR",
    state: "Madhya Pradesh",
    elevationM: 304,
    platforms: 8,
    interlockingType: "Route Relay Electronic Interlocking (RRI)",
    kavachEnabled: true,
    corridorId: "DFC-NORTH-SOUTH",
    isJunction: true,
  },
  {
    name: "Betul",
    code: "BZU",
    lat: 21.9042,
    lng: 77.9014,
    km: 107,
    division: "Nagpur CR",
    zone: "CR",
    state: "Madhya Pradesh",
    elevationM: 658,
    platforms: 3,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-NORTH-SOUTH",
  },
  {
    name: "Badnera Junction",
    code: "BD",
    lat: 20.8657,
    lng: 77.7472,
    km: 1680,
    division: "Nagpur CR",
    zone: "CR",
    state: "Maharashtra",
    elevationM: 331,
    platforms: 4,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-EAST-WEST",
    isJunction: true,
  },
  {
    name: "Akola Junction",
    code: "AK",
    lat: 20.7096,
    lng: 77.0082,
    km: 1760,
    division: "Bhusawal",
    zone: "CR",
    state: "Maharashtra",
    elevationM: 282,
    platforms: 6,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-EAST-WEST",
    isJunction: true,
  },
  {
    name: "Wardha Junction",
    code: "WR",
    lat: 20.7453,
    lng: 78.5975,
    km: 1580,
    division: "Nagpur CR",
    zone: "CR",
    state: "Maharashtra",
    elevationM: 247,
    platforms: 4,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-EAST-WEST",
    isJunction: true,
  },
  {
    name: "Khammam",
    code: "KMT",
    lat: 17.2472,
    lng: 80.1514,
    km: 875,
    division: "Secunderabad",
    zone: "SCR",
    state: "Telangana",
    elevationM: 118,
    platforms: 3,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-NORTH-SOUTH",
  },
  {
    name: "Ramagundam",
    code: "RDM",
    lat: 18.7562,
    lng: 79.5136,
    km: 520,
    division: "Secunderabad",
    zone: "SCR",
    state: "Telangana",
    elevationM: 148,
    platforms: 3,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-NORTH-SOUTH",
  },
  {
    name: "Balasore",
    code: "BLS",
    lat: 21.4934,
    lng: 86.9324,
    km: 116,
    division: "Kharagpur",
    zone: "SER",
    state: "Odisha",
    elevationM: 17,
    platforms: 4,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-EAST-COAST",
  },
  {
    name: "Bhadrak",
    code: "BHC",
    lat: 21.0544,
    lng: 86.4956,
    km: 179,
    division: "Khurda Road",
    zone: "ECOR",
    state: "Odisha",
    elevationM: 17,
    platforms: 4,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-EAST-COAST",
    isJunction: true,
  },
  {
    name: "Cuttack Junction",
    code: "CTC",
    lat: 20.4625,
    lng: 85.8830,
    km: 295,
    division: "Khurda Road",
    zone: "ECOR",
    state: "Odisha",
    elevationM: 28,
    platforms: 5,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-EAST-COAST",
    isJunction: true,
  },
  {
    name: "Khurda Road Junction",
    code: "KUR",
    lat: 20.1878,
    lng: 85.7441,
    km: 342,
    division: "Khurda Road",
    zone: "ECOR",
    state: "Odisha",
    elevationM: 35,
    platforms: 7,
    interlockingType: "Route Relay Interlocking (RRI)",
    kavachEnabled: true,
    corridorId: "DFC-EAST-COAST",
    isJunction: true,
  },
  {
    name: "Brahmapur",
    code: "BAM",
    lat: 19.3149,
    lng: 84.7941,
    km: 490,
    division: "Khurda Road",
    zone: "ECOR",
    state: "Odisha",
    elevationM: 27,
    platforms: 4,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-EAST-COAST",
  },
  {
    name: "Eluru",
    code: "EE",
    lat: 16.7107,
    lng: 81.0952,
    km: 1055,
    division: "Vijayawada",
    zone: "SCR",
    state: "Andhra Pradesh",
    elevationM: 13,
    platforms: 3,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-EAST-COAST",
  },
  {
    name: "Jalgaon Junction",
    code: "JL",
    lat: 21.0077,
    lng: 75.5626,
    km: 1835,
    division: "Bhusawal",
    zone: "CR",
    state: "Maharashtra",
    elevationM: 209,
    platforms: 5,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-EAST-WEST-DANKUNI-SURAT",
    isJunction: true,
  },
  {
    name: "Nandurbar",
    code: "NDB",
    lat: 21.3683,
    lng: 74.2403,
    km: 1940,
    division: "Mumbai WR",
    zone: "WR",
    state: "Maharashtra",
    elevationM: 203,
    platforms: 3,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-EAST-WEST-DANKUNI-SURAT",
  },
  {
    name: "Madgaon Junction (Southern DFC Terminal)",
    code: "MAO",
    lat: 15.2736,
    lng: 73.9780,
    km: 0,
    division: "Karwar",
    zone: "KR",
    state: "Goa",
    elevationM: 9,
    platforms: 4,
    interlockingType: "Solid State Interlocking (SSI)",
    kavachEnabled: true,
    corridorId: "DFC-SOUTHERN",
    isJunction: true,
  },
  {
    name: "Londa Junction",
    code: "LD",
    lat: 15.4674,
    lng: 74.5167,
    km: 84,
    division: "Hubballi",
    zone: "SWR",
    state: "Karnataka",
    elevationM: 652,
    platforms: 3,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-SOUTHERN",
    isJunction: true,
  },
  {
    name: "Hubballi Junction (SWR HQ)",
    code: "UBL",
    lat: 15.3444,
    lng: 75.1481,
    km: 175,
    division: "Hubballi",
    zone: "SWR",
    state: "Karnataka",
    elevationM: 627,
    platforms: 8,
    interlockingType: "Longest Railway Platform Electronic Interlocking",
    kavachEnabled: true,
    corridorId: "DFC-SOUTHERN",
    isJunction: true,
  },
  {
    name: "Hosapete Junction (Hampi Hub)",
    code: "HPT",
    lat: 15.2750,
    lng: 76.3897,
    km: 318,
    division: "Hubballi",
    zone: "SWR",
    state: "Karnataka",
    elevationM: 466,
    platforms: 4,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-SOUTHERN",
    isJunction: true,
  },
  {
    name: "Ballari Junction",
    code: "BAY",
    lat: 15.1394,
    lng: 76.9214,
    km: 383,
    division: "Hubballi",
    zone: "SWR",
    state: "Karnataka",
    elevationM: 450,
    platforms: 4,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-SOUTHERN",
    isJunction: true,
  },
  {
    name: "Renigunta Junction (Tirupati Gateway)",
    code: "RU",
    lat: 13.6508,
    lng: 79.5161,
    km: 748,
    division: "Guntakal",
    zone: "SCR",
    state: "Andhra Pradesh",
    elevationM: 115,
    platforms: 5,
    interlockingType: "Electronic Interlocking (EI)",
    kavachEnabled: true,
    corridorId: "DFC-SOUTHERN",
    isJunction: true,
  },
  {
    name: "Arakkonam Junction",
    code: "AJJ",
    lat: 13.0847,
    lng: 79.6698,
    km: 823,
    division: "Chennai",
    zone: "SR",
    state: "Tamil Nadu",
    elevationM: 85,
    platforms: 6,
    interlockingType: "Route Relay Electronic Interlocking (RRI)",
    kavachEnabled: true,
    corridorId: "DFC-SOUTHERN",
    isJunction: true,
  },
];

// Live Indian Railways Flagship Trains Telemetry across all corridors
export const LIVE_GEO_TRAINS: GeoTrain[] = [
  // --- VANDE BHARAT FLEET ---
  {
    number: "22436",
    name: "Vande Bharat Express (New Delhi ↔ Varanasi)",
    type: "VANDE_BHARAT",
    lat: 26.152,
    lng: 81.251,
    speedKmh: 130,
    headingDeg: 125,
    origin: "New Delhi (NDLS)",
    destination: "Varanasi Jn (BSB)",
    nextStation: "Prayagraj Jn (PRYJ)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "DOUBLE_GREEN",
    corridorId: "GQ-DELHI-HOWRAH",
  },
  {
    number: "22439",
    name: "Vande Bharat Express (New Delhi ↔ SMVD Katra)",
    type: "VANDE_BHARAT",
    lat: 31.251,
    lng: 75.312,
    speedKmh: 130,
    headingDeg: 340,
    origin: "New Delhi (NDLS)",
    destination: "SMVD Katra (SVDK)",
    nextStation: "Ludhiana Jn (LDH)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "DOUBLE_GREEN",
    corridorId: "COR-NORTH-HIGH-SPEED",
  },
  {
    number: "20901",
    name: "Vande Bharat Express (Mumbai ↔ Gandhinagar)",
    type: "VANDE_BHARAT",
    lat: 21.854,
    lng: 73.012,
    speedKmh: 130,
    headingDeg: 355,
    origin: "Mumbai Central (MMCT)",
    destination: "Gandhinagar Capital (GNC)",
    nextStation: "Vadodara Jn (BRC)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "DOUBLE_GREEN",
    corridorId: "GQ-DELHI-MUMBAI",
  },
  {
    number: "20607",
    name: "Vande Bharat Express (Chennai ↔ Mysuru)",
    type: "VANDE_BHARAT",
    lat: 12.981,
    lng: 79.132,
    speedKmh: 130,
    headingDeg: 250,
    origin: "MGR Chennai Central (MAS)",
    destination: "Mysuru Jn (MYS)",
    nextStation: "Katpadi Jn (KPD)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "GREEN",
    corridorId: "GQ-DELHI-CHENNAI",
  },
  {
    number: "22895",
    name: "Vande Bharat Express (Howrah ↔ Puri)",
    type: "VANDE_BHARAT",
    lat: 21.121,
    lng: 86.812,
    speedKmh: 128,
    headingDeg: 215,
    origin: "Howrah Jn (HWH)",
    destination: "Puri (PURI)",
    nextStation: "Bhadrak (BHC)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "DOUBLE_GREEN",
    corridorId: "GQ-CHENNAI-HOWRAH",
  },

  // --- RAJDHANI EXPRESS FLEET ---
  {
    number: "12952",
    name: "Mumbai Rajdhani Express",
    type: "RAJDHANI",
    lat: 24.121,
    lng: 75.321,
    speedKmh: 129,
    headingDeg: 190,
    origin: "New Delhi (NDLS)",
    destination: "Mumbai Central (MMCT)",
    nextStation: "Ratlam Jn (RTM)",
    status: "ON_TIME",
    delayMins: 1,
    signalAspect: "GREEN",
    corridorId: "GQ-DELHI-MUMBAI",
  },
  {
    number: "12302",
    name: "Howrah Rajdhani Express (via Gaya)",
    type: "RAJDHANI",
    lat: 25.121,
    lng: 83.912,
    speedKmh: 130,
    headingDeg: 105,
    origin: "New Delhi (NDLS)",
    destination: "Howrah Jn (HWH)",
    nextStation: "Gaya Jn (GAYA)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "DOUBLE_GREEN",
    corridorId: "GQ-DELHI-HOWRAH",
  },
  {
    number: "22692",
    name: "Bengaluru Rajdhani Express",
    type: "RAJDHANI",
    lat: 19.854,
    lng: 78.821,
    speedKmh: 125,
    headingDeg: 180,
    origin: "Hazrat Nizamuddin (NZM)",
    destination: "KSR Bengaluru (SBC)",
    nextStation: "Secunderabad Jn (SC)",
    status: "ON_TIME",
    delayMins: 2,
    signalAspect: "GREEN",
    corridorId: "DIAG-DELHI-BENGALURU",
  },
  {
    number: "12434",
    name: "Chennai Rajdhani Express",
    type: "RAJDHANI",
    lat: 18.214,
    lng: 79.854,
    speedKmh: 128,
    headingDeg: 165,
    origin: "Hazrat Nizamuddin (NZM)",
    destination: "MGR Chennai Central (MAS)",
    nextStation: "Warangal (WL)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "GREEN",
    corridorId: "GQ-DELHI-CHENNAI",
  },
  {
    number: "12424",
    name: "Dibrugarh Rajdhani Express",
    type: "RAJDHANI",
    lat: 26.412,
    lng: 89.215,
    speedKmh: 118,
    headingDeg: 80,
    origin: "New Delhi (NDLS)",
    destination: "Dibrugarh (DBRG)",
    nextStation: "New Jalpaiguri (NJP)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "GREEN",
    corridorId: "COR-NORTHEAST-TRUNK",
  },

  // --- SHATABDI & GATIMAAN FLEET ---
  {
    number: "12050",
    name: "Gatimaan Express (Fastest Commercial Train)",
    type: "SHATABDI_GATIMAAN",
    lat: 27.352,
    lng: 77.811,
    speedKmh: 158,
    headingDeg: 145,
    origin: "Hazrat Nizamuddin (NZM)",
    destination: "Agra Cantt (AGC)",
    nextStation: "Agra Cantt (AGC)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "DOUBLE_GREEN",
    corridorId: "GQ-DELHI-CHENNAI",
  },
  {
    number: "12002",
    name: "Bhopal Shatabdi Express",
    type: "SHATABDI_GATIMAAN",
    lat: 25.821,
    lng: 78.312,
    speedKmh: 150,
    headingDeg: 180,
    origin: "New Delhi (NDLS)",
    destination: "Rani Kamalapati (RKMP)",
    nextStation: "Gwalior Jn (GWL)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "DOUBLE_GREEN",
    corridorId: "GQ-DELHI-CHENNAI",
  },
  {
    number: "12004",
    name: "Lucknow Swarna Shatabdi Express",
    type: "SHATABDI_GATIMAAN",
    lat: 26.654,
    lng: 79.512,
    speedKmh: 130,
    headingDeg: 115,
    origin: "New Delhi (NDLS)",
    destination: "Lucknow Charbagh (LKO)",
    nextStation: "Kanpur Central (CNB)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "GREEN",
    corridorId: "GQ-DELHI-HOWRAH",
  },

  // --- PREMIER SUPERFAST & EXPRESS SERVICES ---
  {
    number: "12616",
    name: "Grand Trunk (GT) Express",
    type: "SUPERFAST",
    lat: 22.124,
    lng: 78.412,
    speedKmh: 110,
    headingDeg: 175,
    origin: "New Delhi (NDLS)",
    destination: "MGR Chennai Central (MAS)",
    nextStation: "Nagpur Jn (NGP)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "GREEN",
    corridorId: "GQ-DELHI-CHENNAI",
  },
  {
    number: "12626",
    name: "Kerala Express",
    type: "SUPERFAST",
    lat: 14.215,
    lng: 79.124,
    speedKmh: 110,
    headingDeg: 180,
    origin: "New Delhi (NDLS)",
    destination: "Thiruvananthapuram (TVC)",
    nextStation: "Tirupati (TPTY)",
    status: "ON_TIME",
    delayMins: 3,
    signalAspect: "GREEN",
    corridorId: "GQ-DELHI-CHENNAI",
  },
  {
    number: "12842",
    name: "Coromandel Express",
    type: "SUPERFAST",
    lat: 18.521,
    lng: 83.912,
    speedKmh: 120,
    headingDeg: 215,
    origin: "Howrah Jn (HWH)",
    destination: "MGR Chennai Central (MAS)",
    nextStation: "Visakhapatnam Jn (VSKP)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "DOUBLE_GREEN",
    corridorId: "GQ-CHENNAI-HOWRAH",
  },
  {
    number: "12262",
    name: "Mumbai CSMT ↔ Howrah Duronto",
    type: "SUPERFAST",
    lat: 21.312,
    lng: 83.214,
    speedKmh: 122,
    headingDeg: 85,
    origin: "Mumbai CSMT",
    destination: "Howrah Jn (HWH)",
    nextStation: "Bilaspur Jn (BSP)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "DOUBLE_GREEN",
    corridorId: "GQ-MUMBAI-HOWRAH",
  },
  {
    number: "12056",
    name: "Jan Shatabdi Express",
    type: "EXPRESS",
    lat: 28.512,
    lng: 77.274,
    speedKmh: 104,
    headingDeg: 350,
    origin: "Dehradun (DDN)",
    destination: "New Delhi (NDLS)",
    nextStation: "Hazrat Nizamuddin (NZM)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "GREEN",
    corridorId: "GQ-DELHI-MUMBAI",
  },
  {
    number: "16345",
    name: "Netravati Express (Konkan Route)",
    type: "EXPRESS",
    lat: 14.124,
    lng: 74.452,
    speedKmh: 95,
    headingDeg: 160,
    origin: "Lokmanya Tilak Terminus (LTT)",
    destination: "Thiruvananthapuram (TVC)",
    nextStation: "Udupi (UD)",
    status: "ON_TIME",
    delayMins: 5,
    signalAspect: "GREEN",
    corridorId: "COR-KONKAN-COAST",
  },

  // --- HEAVY DEDICATED FREIGHT & MAINTENANCE SPECIALS ---
  {
    number: "PYTHON-01",
    name: "Long-Haul Double Stack Container Freight (WDFC)",
    type: "FREIGHT_CONTAINER",
    lat: 26.812,
    lng: 75.412,
    speedKmh: 75,
    headingDeg: 210,
    origin: "Dadri WDFC Freight Terminal",
    destination: "Jawaharlal Nehru Port Trust (JNPT)",
    nextStation: "Phulera Junction",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "GREEN",
    corridorId: "GQ-DELHI-MUMBAI",
  },
  {
    number: "BCN/E-401",
    name: "Covered Fertilizer Rake (BCN)",
    type: "FREIGHT_CONTAINER",
    lat: 27.4924,
    lng: 77.6737,
    speedKmh: 0,
    headingDeg: 170,
    origin: "Tughlakabad DFC Yard",
    destination: "Bhusawal Goods Shed",
    nextStation: "Mathura Jn (Held Loop Line 3)",
    status: "HELD_LOOP",
    delayMins: 11,
    signalAspect: "YELLOW",
    corridorId: "GQ-DELHI-CHENNAI",
  },
  {
    number: "BOXN-42",
    name: "Heavy Rake 4200T Coal Rake",
    type: "FREIGHT_CONTAINER",
    lat: 27.85,
    lng: 77.41,
    speedKmh: 48,
    headingDeg: 165,
    origin: "Chandausi Yard",
    destination: "Kota Thermal Power Station",
    nextStation: "Kosi Kalan (KSV)",
    status: "DELAYED",
    delayMins: 75,
    signalAspect: "YELLOW",
    corridorId: "GQ-DELHI-MUMBAI",
  },
  {
    number: "BTPN-POL",
    name: "Petroleum Tanker Rake (Indian Oil)",
    type: "FREIGHT_CONTAINER",
    lat: 28.312,
    lng: 77.312,
    speedKmh: 65,
    headingDeg: 340,
    origin: "Mathura Refinery Siding",
    destination: "Panipat Depot",
    nextStation: "Faridabad (FDB)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "GREEN",
    corridorId: "GQ-DELHI-MUMBAI",
  },
  {
    number: "DETC-04",
    name: "8-Wheeler Tower Wagon (25kV OHE)",
    type: "MAINTENANCE_SPECIAL",
    lat: 27.68,
    lng: 77.52,
    speedKmh: 15,
    headingDeg: 135,
    origin: "Mathura Traction Depot",
    destination: "Chhata OHE Section",
    nextStation: "KM 142.4 OHE Power Cut Block",
    status: "WORK_ZONE",
    delayMins: 0,
    signalAspect: "RED",
    corridorId: "GQ-DELHI-CHENNAI",
  },

  // --- DEDICATED FREIGHT CORRIDORS (DFC) PYTHON & CONTAINER FLEET ---
  {
    number: "EDFC-701",
    name: "EDFC Heavy Coal Super Rake (12,000T)",
    type: "FREIGHT_CONTAINER",
    lat: 25.421,
    lng: 82.512,
    speedKmh: 90,
    headingDeg: 110,
    origin: "Sahnewal DFC Yard (SNL)",
    destination: "Dankuni DFC Terminal (DKAE)",
    nextStation: "Pt. Deen Dayal Upadhyaya (DDU)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "DOUBLE_GREEN",
    corridorId: "DFC-EASTERN",
  },
  {
    number: "WDFC-902",
    name: "WDFC Double-Stack Python Container (WAG-12B Twin)",
    type: "FREIGHT_CONTAINER",
    lat: 24.521,
    lng: 73.112,
    speedKmh: 95,
    headingDeg: 195,
    origin: "Dadri Multimodal Hub (DER)",
    destination: "JNPT Nava Sheva Port (JNPT)",
    nextStation: "Palanpur Jn (PNU)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "DOUBLE_GREEN",
    corridorId: "DFC-WESTERN",
  },
  {
    number: "EWDFC-504",
    name: "East-West DFC Heavy Steel Coil Express",
    type: "FREIGHT_CONTAINER",
    lat: 21.214,
    lng: 81.341,
    speedKmh: 82,
    headingDeg: 260,
    origin: "Dankuni Yard (DKAE)",
    destination: "Bhusawal Goods Terminal (BSL)",
    nextStation: "Raipur Jn (R)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "GREEN",
    corridorId: "DFC-EAST-WEST",
  },
  {
    number: "NSDFC-301",
    name: "North-South DFC Maruti Automobile Carrier",
    type: "FREIGHT_CONTAINER",
    lat: 19.412,
    lng: 79.621,
    speedKmh: 85,
    headingDeg: 165,
    origin: "Itarsi Jn (ET)",
    destination: "Vijayawada Jn (BZA)",
    nextStation: "Ballarshah (BPQ)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "GREEN",
    corridorId: "DFC-NORTH-SOUTH",
  },
  {
    number: "ECDFC-402",
    name: "East Coast DFC Iron Ore Rake (BOXNHL)",
    type: "FREIGHT_CONTAINER",
    lat: 19.854,
    lng: 85.124,
    speedKmh: 80,
    headingDeg: 210,
    origin: "Kharagpur DFC Junction (KGP)",
    destination: "Vijayawada Jn (BZA)",
    nextStation: "Brahmapur (BAM)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "DOUBLE_GREEN",
    corridorId: "DFC-EAST-COAST",
  },
  {
    number: "SDFC-201",
    name: "Southern DFC Port Container Express",
    type: "FREIGHT_CONTAINER",
    lat: 14.851,
    lng: 76.812,
    speedKmh: 75,
    headingDeg: 115,
    origin: "Madgaon Port Terminal (MAO)",
    destination: "Chennai Central Harbor (MAS)",
    nextStation: "Guntakal Jn (GTL)",
    status: "ON_TIME",
    delayMins: 0,
    signalAspect: "GREEN",
    corridorId: "DFC-SOUTHERN",
  },
];

const LOCAL_STORAGE_API_KEY = "indian_rail_api_key";
const LOCAL_STORAGE_GOOGLE_MAPS_KEY = "google_maps_api_key";

export function getStoredIndianRailApiKey(): string {
  if (typeof window === "undefined") return "";
  return localStorage.getItem(LOCAL_STORAGE_API_KEY) || "";
}

export function setStoredIndianRailApiKey(key: string): void {
  if (typeof window === "undefined") return;
  localStorage.setItem(LOCAL_STORAGE_API_KEY, key.trim());
}

export function getStoredGoogleMapsApiKey(): string {
  if (typeof window === "undefined") return "";
  const key =
    localStorage.getItem(LOCAL_STORAGE_GOOGLE_MAPS_KEY) ||
    (import.meta as any).env?.VITE_GOOGLE_MAPS_API_KEY ||
    "";
  if (key.startsWith("AQ.Ab8")) return "";
  return key;
}

export function setStoredGoogleMapsApiKey(key: string): void {
  if (typeof window === "undefined") return;
  localStorage.setItem(LOCAL_STORAGE_GOOGLE_MAPS_KEY, key.trim());
}

/**
 * Google Maps Dark Theme styling matching Railwire command telemetry
 */
export const GOOGLE_MAPS_DARK_STYLE = [
  { elementType: "geometry", stylers: [{ color: "#0b1319" }] },
  { elementType: "labels.text.stroke", stylers: [{ color: "#0b1319" }, { weight: 2 }] },
  { elementType: "labels.text.fill", stylers: [{ color: "#748892" }] },
  {
    featureType: "administrative.locality",
    elementType: "labels.text.fill",
    stylers: [{ color: "#a8bdc7" }],
  },
  {
    featureType: "poi",
    elementType: "labels.text.fill",
    stylers: [{ color: "#617782" }],
  },
  {
    featureType: "poi.park",
    elementType: "geometry",
    stylers: [{ color: "#0c1a21" }],
  },
  {
    featureType: "road",
    elementType: "geometry",
    stylers: [{ color: "#16232b" }],
  },
  {
    featureType: "road",
    elementType: "geometry.stroke",
    stylers: [{ color: "#121b21" }],
  },
  {
    featureType: "road.highway",
    elementType: "geometry",
    stylers: [{ color: "#1a2c36" }],
  },
  {
    featureType: "transit",
    elementType: "geometry",
    stylers: [{ color: "#1f3340" }],
  },
  {
    featureType: "transit.station",
    elementType: "labels.text.fill",
    stylers: [{ color: "#6ee7f9" }],
  },
  {
    featureType: "water",
    elementType: "geometry",
    stylers: [{ color: "#070e14" }],
  },
  {
    featureType: "water",
    elementType: "labels.text.fill",
    stylers: [{ color: "#395260" }],
  },
];

/**
 * Dynamically loads Google Maps JavaScript API script
 */
export function loadGoogleMapsScript(apiKey: string): Promise<boolean> {
  return new Promise((resolve) => {
    if (typeof window === "undefined") {
      resolve(false);
      return;
    }
    if ((window as any).google && (window as any).google.maps) {
      resolve(true);
      return;
    }
    const cleanKey = apiKey.trim();
    const existing = document.getElementById("google-maps-api-script") as HTMLScriptElement | null;
    if (existing) {
      if ((window as any).google && (window as any).google.maps) {
        resolve(true);
      } else {
        existing.addEventListener("load", () => resolve(true));
        existing.addEventListener("error", () => resolve(false));
      }
      return;
    }

    const script = document.createElement("script");
    script.id = "google-maps-api-script";
    script.src = `https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(
      cleanKey
    )}&libraries=places,geometry`;
    script.async = true;
    script.defer = true;
    script.onload = () => {
      resolve(true);
    };
    script.onerror = () => {
      resolve(false);
    };
    document.head.appendChild(script);
  });
}

/**
 * Fetches real station coordinates from IndianRailAPI
 * http://indianrailapi.com/api/v2/StationLocationOnMap/apikey/<apikey>/StationCode/<StationCode>
 */
export async function fetchStationLocationFromApi(
  stationCode: string,
  apiKey?: string
): Promise<{ lat: number; lng: number; raw?: any } | null> {
  const key = (apiKey || getStoredIndianRailApiKey()).trim();
  if (!key || key === "<apikey>") {
    return null;
  }

  const url = `http://indianrailapi.com/api/v2/StationLocationOnMap/apikey/${encodeURIComponent(
    key
  )}/StationCode/${encodeURIComponent(stationCode.toUpperCase())}`;

  try {
    const res = await fetch(url);
    if (!res.ok) return null;
    const data = await res.json();

    if (data && (data.Latitude || data.latitude || data.lat)) {
      const lat = parseFloat(data.Latitude || data.latitude || data.lat);
      const lng = parseFloat(data.Longitude || data.longitude || data.lng || data.long);
      if (!isNaN(lat) && !isNaN(lng)) {
        return { lat, lng, raw: data };
      }
    }
  } catch (err) {
    console.warn("IndianRailAPI fetch failed, falling back to local registry:", err);
  }

  return null;
}
